export const COMMON_BREEDS = [
  "SRD (Sem Raça Definida)",
  "Akita Inu",
  "Basset Hound",
  "Beagle",
  "Bichon Frisé",
  "Boiadeiro Australiano (Blue Heeler)",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Bull Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Inglês",
  "Cocker Spaniel Americano",
  "Corgi (Welsh Corgi Pembroke)",
  "Dachshund / Salsicha",
  "Dálmata",
  "Doberman",
  "Dogo Argentino",
  "Fila Brasileiro",
  "Golden Retriever",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lhasa Apso",
  "Malamute do Alasca",
  "Maltês",
  "Mastim Napolitano",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga Malinois",
  "Pastor Branco Suíço",
  "Pastor de Shetland",
  "Pequinês",
  "Pinscher Miniatura",
  "Pitbull (American Pit Bull Terrier)",
  "Pointer Inglês",
  "Poodle Toy",
  "Poodle Miniatura",
  "Poodle Standard",
  "Pug",
  "Rottweiler",
  "Samoeida",
  "São Bernardo",
  "Schnauzer Miniatura",
  "Setter Irlandês",
  "Shar-Pei",
  "Shih Tzu",
  "Spitz Alemão Anão / Lulu da Pomerânia",
  "Staffordshire Bull Terrier",
  "Terra Nova",
  "Weimaraner",
  "Yorkshire Terrier",
  "Outra"
];
