export const COMMON_BREEDS = [
  "SRD (Sem Raça Definida)",
  "Akita Inu",
  "American Bully",
  "Basset Hound",
  "Beagle",
  "Bernese Mountain Dog (Boiadeiro Bernês)",
  "Bichon Frisé",
  "Boiadeiro Australiano (Blue Heeler)",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Bulldog Campeiro",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Bull Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Inglês",
  "Cocker Spaniel Americano",
  "Corgi (Welsh Corgi Pembroke)",
  "Dachshund / Salsicha",
  "Dálmata",
  "Doberman",
  "Dogo Argentino",
  "Fila Brasileiro",
  "Fox Paulistinha (Terrier Brasileiro)",
  "Galgo Italiano",
  "Galgo Whippet",
  "Golden Retriever",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lhasa Apso",
  "Malamute do Alasca",
  "Maltês",
  "Mastim Napolitano",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga Malinois",
  "Pastor Branco Suíço",
  "Pastor de Shetland",
  "Pequinês",
  "Pinscher Miniatura",
  "Pitbull (American Pit Bull Terrier)",
  "Pointer Inglês",
  "Poodle Toy",
  "Poodle Miniatura",
  "Poodle Standard",
  "Pug",
  "Rottweiler",
  "Samoieda",
  "São Bernardo",
  "Schnauzer Miniatura",
  "Setter Irlandês",
  "Shar-Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Spitz Alemão Anão / Lulu da Pomerânia",
  "Staffordshire Americano (Amstaff)",
  "Staffordshire Bull Terrier",
  "Terra Nova",
  "Weimaraner",
  "Whippet",
  "Yorkshire Terrier",
  "Outra"
];
