export const COMMON_BREEDS = [
  "SRD (Sem Raça Definida)",
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita Inu",
  "American Bully",
  "Anatolian Shepherd (Pastor da Anatólia)",
  "Australian Kelpie (Kelpie Australiano)",
  "Azawakh",
  "Barbet",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Beauceron (Pastor de Beauce)",
  "Bedlington Terrier",
  "Bernese Mountain Dog (Boiadeiro Bernês)",
  "Bichon Frisé",
  "Black and Tan Coonhound",
  "Bloodhound",
  "Boerboel",
  "Boiadeiro Australiano (Blue Heeler)",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier de Flandres",
  "Boxer",
  "Braco Alemão",
  "Braco Italiano",
  "Brussels Griffon",
  "Bulldog Americano",
  "Bulldog Campeiro",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Bullmastiff",
  "Bull Terrier",
  "Cairn Terrier",
  "Cane Corso",
  "Cão de Água Português",
  "Cão de Faraó (Pharaoh Hound)",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chow Chow",
  "Clumber Spaniel",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Corgi (Welsh Corgi Pembroke)",
  "Coton de Tulear",
  "Curly-Coated Retriever",
  "Dachshund / Salsicha",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Deerhound (Galgo Escocês)",
  "Doberman",
  "Dogo Argentino",
  "Dogue Alemão",
  "Dogue de Bordeaux",
  "Fila Brasileiro",
  "Fox Paulistinha (Terrier Brasileiro)",
  "Fox Terrier Pelo Duro",
  "Fox Terrier Pelo Liso",
  "Foxhound Americano",
  "Foxhound Inglês",
  "Galgo Italiano",
  "Galgo Whippet",
  "Golden Retriever",
  "Greyhound (Galgo Inglês)",
  "Havaneiro (Havanese)",
  "Hovawart",
  "Husky Siberiano",
  "Irish Wolfhound",
  "Jack Russell Terrier",
  "Kangal",
  "Keeshond",
  "Kerry Blue Terrier",
  "Komondor",
  "Kuvasz",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Leão da Rodésia (Rhodesian Ridgeback)",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen (Pequeno Cão Leão)",
  "Malamute do Alasca",
  "Maltês",
  "Maltipoo",
  "Maremmano (Pastor Maremmano)",
  "Mastiff Inglês",
  "Mastim Napolitano",
  "Mastim Tibetano",
  "Norfolk Terrier",
  "Old English Sheepdog",
  "Otterhound",
  "Ovelheiro Gaúcho",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga Groenendael",
  "Pastor Belga Malinois",
  "Pastor Belga Tervueren",
  "Pastor Branco Suíço",
  "Pastor de Shetland",
  "Pequinês",
  "Petit Basset Griffon Vendéen",
  "Pinscher Miniatura",
  "Pitbull (American Pit Bull Terrier)",
  "Podengo Ibiçano",
  "Podengo Português",
  "Pointer Inglês",
  "Poodle Miniatura",
  "Poodle Standard",
  "Poodle Toy",
  "Pug",
  "Puli",
  "Pumi",
  "Rottweiler",
  "Saluki",
  "Samoieda",
  "São Bernardo",
  "Schapendoes",
  "Schipperke",
  "Schnauzer Miniatura",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Setter Irlandês",
  "Shar-Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Silky Terrier",
  "Spinone Italiano",
  "Spitz Alemão Anão / Lulu da Pomerânia",
  "Staffordshire Americano (Amstaff)",
  "Staffordshire Bull Terrier",
  "Terra Nova",
  "Tibetan Spaniel (Spaniel Tibetano)",
  "Tibetan Terrier",
  "Veadeiro Pampeano",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier (Westie)",
  "Whippet",
  "Xoloitzcuintli (Cão Pelado Mexicano)",
  "Yorkshire Terrier",
  "Outra"
];
