export type DogFoodLifeStage = 'Adulto' | 'Filhote' | 'Senior';

export type DogFoodOption = {
  brand: string;
  line: string;
  lifeStage: DogFoodLifeStage;
};

export const DOG_FOOD_OPTIONS: DogFoodOption[] = [
  { brand: 'Acana', line: 'Adult Small Breed', lifeStage: 'Adulto' },
  { brand: 'Acana', line: 'Heritage Adult', lifeStage: 'Adulto' },
  { brand: 'Acana', line: 'Puppy Small Breed', lifeStage: 'Filhote' },
  { brand: 'Acana', line: 'Regionals Wild Prairie', lifeStage: 'Adulto' },
  { brand: 'Alpo', line: 'Caes Adultos', lifeStage: 'Adulto' },
  { brand: 'Alpo', line: 'Caes Filhotes', lifeStage: 'Filhote' },
  { brand: 'Biofresh', line: 'Adultos Racas Medias e Grandes', lifeStage: 'Adulto' },
  { brand: 'Biofresh', line: 'Adultos Racas Pequenas e Mini', lifeStage: 'Adulto' },
  { brand: 'Biofresh', line: 'Filhotes', lifeStage: 'Filhote' },
  { brand: 'Biofresh', line: 'Sache Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Dog Chow', line: 'Adultos Racas Medias e Grandes', lifeStage: 'Adulto' },
  { brand: 'Dog Chow', line: 'Adultos Racas Mini e Pequenas', lifeStage: 'Adulto' },
  { brand: 'Dog Chow', line: 'Filhotes Racas Medias e Grandes', lifeStage: 'Filhote' },
  { brand: 'Dog Chow', line: 'Filhotes Racas Mini e Pequenas', lifeStage: 'Filhote' },
  { brand: 'Eukanuba', line: 'Adult Large Breed', lifeStage: 'Adulto' },
  { brand: 'Eukanuba', line: 'Adult Medium Breed', lifeStage: 'Adulto' },
  { brand: 'Eukanuba', line: 'Adult Small Breed', lifeStage: 'Adulto' },
  { brand: 'Eukanuba', line: 'Puppy Medium Breed', lifeStage: 'Filhote' },
  { brand: 'Eukanuba', line: 'Puppy Small Breed', lifeStage: 'Filhote' },
  { brand: 'Farmina N&D', line: 'Ancestral Grain Adulto Cordeiro', lifeStage: 'Adulto' },
  { brand: 'Farmina N&D', line: 'Ancestral Grain Adulto Frango', lifeStage: 'Adulto' },
  { brand: 'Farmina N&D', line: 'Ancestral Grain Filhote Cordeiro', lifeStage: 'Filhote' },
  { brand: 'Farmina N&D', line: 'Prime Adulto Frango Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Farmina N&D', line: 'Prime Filhote Frango Racas Pequenas', lifeStage: 'Filhote' },
  { brand: 'Farmina N&D', line: 'Tropical Selection Filhote Suino', lifeStage: 'Filhote' },
  { brand: 'Farmina N&D', line: 'White Adulto Mini Peixe', lifeStage: 'Adulto' },
  { brand: 'Formula Natural', line: 'Fresh Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Formula Natural', line: 'Life Adultos Medio e Grande', lifeStage: 'Adulto' },
  { brand: 'Formula Natural', line: 'Life Filhotes', lifeStage: 'Filhote' },
  { brand: 'Golden', line: 'Formula Adultos Carne e Arroz', lifeStage: 'Adulto' },
  { brand: 'Golden', line: 'Formula Adultos Frango e Arroz', lifeStage: 'Adulto' },
  { brand: 'Golden', line: 'Formula Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Golden', line: 'Formula Adultos Salmao e Arroz', lifeStage: 'Adulto' },
  { brand: 'Golden', line: 'Formula Filhotes Carne e Arroz', lifeStage: 'Filhote' },
  { brand: 'Golden', line: 'Formula Filhotes Frango e Arroz', lifeStage: 'Filhote' },
  { brand: 'Guabi Natural', line: 'Adulto Light Mini e Pequena', lifeStage: 'Adulto' },
  { brand: 'Guabi Natural', line: 'Adulto Medio Cordeiro e Aveia', lifeStage: 'Adulto' },
  { brand: 'Guabi Natural', line: 'Adulto Medio Frango e Lentilha', lifeStage: 'Adulto' },
  { brand: 'Guabi Natural', line: 'Adulto Mini e Pequeno Cordeiro e Aveia', lifeStage: 'Adulto' },
  { brand: 'Guabi Natural', line: 'Adulto Mini e Pequeno Frango e Arroz', lifeStage: 'Adulto' },
  { brand: 'Guabi Natural', line: 'Filhote Medio Frango e Arroz', lifeStage: 'Filhote' },
  { brand: 'Guabi Natural', line: 'Filhote Mini e Pequeno Frango e Arroz', lifeStage: 'Filhote' },
  { brand: "Hill's", line: 'Prescription Diet i/d Gastrointestinal', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Prescription Diet k/d Renal', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Prescription Diet w/d Controle de Peso', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Prescription Diet z/d Alergia Alimentar', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Science Diet Adulto Light', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Science Diet Adulto Pequeno e Mini', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Science Diet Adulto Racas Grandes', lifeStage: 'Adulto' },
  { brand: "Hill's", line: 'Science Diet Filhote Pequeno e Mini', lifeStage: 'Filhote' },
  { brand: "Hill's", line: 'Science Diet Filhote Racas Grandes', lifeStage: 'Filhote' },
  { brand: "Hill's", line: 'Science Diet Senior Small Paws', lifeStage: 'Senior' },
  { brand: 'Magnus', line: 'Premium Caes Adultos', lifeStage: 'Adulto' },
  { brand: 'Magnus', line: 'Premium Caes Filhotes', lifeStage: 'Filhote' },
  { brand: 'Orijen', line: 'Original Adulto', lifeStage: 'Adulto' },
  { brand: 'Orijen', line: 'Puppy', lifeStage: 'Filhote' },
  { brand: 'Orijen', line: 'Regional Red Adulto', lifeStage: 'Adulto' },
  { brand: 'Orijen', line: 'Six Fish Adulto', lifeStage: 'Adulto' },
  { brand: 'Pedigree', line: 'Adultos Racas Medias e Grandes', lifeStage: 'Adulto' },
  { brand: 'Pedigree', line: 'Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Pedigree', line: 'Filhotes Racas Medias e Grandes', lifeStage: 'Filhote' },
  { brand: 'Pedigree', line: 'Sache Adultos Frango ao Molho', lifeStage: 'Adulto' },
  { brand: 'Pedigree', line: 'Senior', lifeStage: 'Senior' },
  { brand: 'Premier Pet', line: 'Formula Adultos Racas Grandes', lifeStage: 'Adulto' },
  { brand: 'Premier Pet', line: 'Formula Adultos Racas Medias', lifeStage: 'Adulto' },
  { brand: 'Premier Pet', line: 'Formula Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Premier Pet', line: 'Formula Filhotes Ambientes Internos Racas Pequenas', lifeStage: 'Filhote' },
  { brand: 'Premier Pet', line: 'Formula Filhotes Indoor Racas Pequenas', lifeStage: 'Filhote' },
  { brand: 'Premier Pet', line: 'Formula Filhotes Racas Grandes', lifeStage: 'Filhote' },
  { brand: 'Premier Pet', line: 'Formula Filhotes Racas Medias', lifeStage: 'Filhote' },
  { brand: 'Premier Pet', line: 'Formula Filhotes Racas Pequenas', lifeStage: 'Filhote' },
  { brand: 'Premier Pet', line: 'Light Adultos', lifeStage: 'Adulto' },
  { brand: 'Premier Pet', line: 'Nutricao Clinica Obesidade', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Adult Medium and Large Breed', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Adult Medium & Large Breed', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Adult Sensitive Skin', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Adult Small and Toy Breed', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Adult Small & Toy Breed', lifeStage: 'Adulto' },
  { brand: 'Purina Pro Plan', line: 'Puppy Large Breed', lifeStage: 'Filhote' },
  { brand: 'Purina Pro Plan', line: 'Puppy Small and Toy Breed', lifeStage: 'Filhote' },
  { brand: 'Purina Pro Plan', line: 'Puppy Small & Toy Breed', lifeStage: 'Filhote' },
  { brand: 'Purina Pro Plan', line: 'Sport All Sizes', lifeStage: 'Adulto' },
  { brand: 'Quatree', line: 'Gourmet Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Quatree', line: 'Gourmet Filhotes Carne e Leite', lifeStage: 'Filhote' },
  { brand: 'Quatree', line: 'Supreme Adultos Racas Medias e Grandes', lifeStage: 'Adulto' },
  { brand: 'Quatree', line: 'Supreme Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Quatree', line: 'Supreme Filhotes Racas Medias e Grandes', lifeStage: 'Filhote' },
  { brand: 'Quatree', line: 'Supreme Filhotes Racas Pequenas', lifeStage: 'Filhote' },
  { brand: 'Royal Canin', line: 'Gastrointestinal', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Giant Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Giant Puppy', lifeStage: 'Filhote' },
  { brand: 'Royal Canin', line: 'Maxi Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Maxi Puppy', lifeStage: 'Filhote' },
  { brand: 'Royal Canin', line: 'Maxi Sterilised', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Medium Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Medium Ageing 10+', lifeStage: 'Senior' },
  { brand: 'Royal Canin', line: 'Medium Puppy', lifeStage: 'Filhote' },
  { brand: 'Royal Canin', line: 'Medium Sterilised', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Mini Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Mini Ageing 12+', lifeStage: 'Senior' },
  { brand: 'Royal Canin', line: 'Mini Indoor Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Mini Puppy', lifeStage: 'Filhote' },
  { brand: 'Royal Canin', line: 'Mini Sterilised', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Renal Caes', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Sache Mini Adult', lifeStage: 'Adulto' },
  { brand: 'Royal Canin', line: 'Satiety Support Lata Obesidade', lifeStage: 'Adulto' },
  { brand: 'Special Dog', line: 'Junior Filhotes', lifeStage: 'Filhote' },
  { brand: 'Special Dog', line: 'Premium Adultos Carne', lifeStage: 'Adulto' },
  { brand: 'Special Dog', line: 'Ultralife Adultos Racas Pequenas', lifeStage: 'Adulto' },
  { brand: 'Special Dog', line: 'Ultralife Senior 7+', lifeStage: 'Senior' },
  { brand: 'Taste of the Wild', line: 'High Prairie Adulto Bisao', lifeStage: 'Adulto' },
  { brand: 'Taste of the Wild', line: 'High Prairie Filhote', lifeStage: 'Filhote' },
  { brand: 'Taste of the Wild', line: 'Pacific Stream Adulto Salmao', lifeStage: 'Adulto' },
  { brand: 'Taste of the Wild', line: 'Sierra Mountain Adulto Cordeiro', lifeStage: 'Adulto' },
];

export const DOG_FOOD_BRANDS = Array.from(new Set(DOG_FOOD_OPTIONS.map((item) => item.brand)));
export const DOG_FOOD_LINES = Array.from(new Set(DOG_FOOD_OPTIONS.map((item) => item.line)));

export function getDogFoodLinesByBrand(brand: string): string[] {
  return DOG_FOOD_OPTIONS
    .filter((item) => item.brand === brand)
    .map((item) => item.line);
}

export function getDogFoodLifeStage(brand: string, line: string): DogFoodLifeStage | undefined {
  return DOG_FOOD_OPTIONS.find((item) => item.brand === brand && item.line === line)?.lifeStage;
}
